# Generated by Django 4.2.27 on 2026-01-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_contact_person_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='teams', to='clients.client'),
        ),
    ]
