# Generated by Django 4.2.27 on 2026-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analyst',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst')], default='ANALYST', max_length=10),
        ),
        migrations.AddField(
            model_name='analyst',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
