# Generated by Django 4.2.27 on 2026-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysts', '0002_analyst_email_analyst_role_analyst_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ANALYST', 'Analyst'), ('TEAM_LEADER', 'Team Leader')], default='ANALYST', max_length=20),
        ),
    ]
