# Generated by Django 4.2.27 on 2026-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='email',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
