# Generated by Django 4.2.27 on 2026-01-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_client_name'),
        ('analysts', '0004_analyst_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('endorsement_date', models.DateField()),
                ('recall_date', models.DateField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to='analysts.analyst')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='clients.client')),
            ],
            options={
                'ordering': ['-endorsement_date'],
                'unique_together': {('client', 'account_number')},
            },
        ),
    ]
