# Generated by Django 4.2.27 on 2026-01-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_client_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_schemas', to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_header', models.CharField(max_length=255)),
                ('target_field', models.CharField(choices=[('account_number', 'Account Number'), ('account_name', 'Account Name'), ('endorsement_date', 'Endorsement Date'), ('recall_date', 'Recall Date'), ('outstanding_balance', 'Outstanding Balance'), ('data_payload', 'Extra Data (JSON)')], max_length=50)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('DECIMAL', 'Decimal'), ('DATE', 'Date')], default='STRING', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='accounts.importschema')),
            ],
            options={
                'unique_together': {('schema', 'csv_header')},
            },
        ),
    ]
