# Generated by Django 4.2.27 on 2026-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_importschema_columnmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='importschema',
            name='display_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for Analyst View columns'),
        ),
    ]
