# Generated by Django 4.2.27 on 2026-02-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_importbatch_account_import_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('WORKING', 'Working'), ('RETURNED', 'Returned'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
