# Generated by Django 4.2.27 on 2026-02-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysts', '0004_analyst_clients'),
        ('accounts', '0005_alter_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CALL', 'Call'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VISIT', 'Field Visit'), ('SKIP', 'Skip Trace'), ('NOTE', 'Note')], default='NOTE', max_length=20)),
                ('outcome', models.CharField(choices=[('ANSWERED', 'Answered'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('DISCONNECTED', 'Disconnected'), ('PTP', 'Promise to Pay'), ('CALLBACK', 'Callback'), ('REFUSAL', 'Refusal'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysts.analyst')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountPTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ptp_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BROKEN', 'Broken'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptps', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysts.analyst')),
                ('source_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ptp', to='accounts.activitylog')),
            ],
            options={
                'ordering': ['-ptp_date'],
            },
        ),
    ]
